name: Run OpenSSF Scorecard

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run your tool
      run: |
        ./OpenSSF Scorecard --results-path ./results
