name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest


    - name: Run OpenSSF Scorecard
      uses: ossf/scorecard-action@v2.4.0
      with:
        entryPoint: ./scorecard
        results_file: ./scorecard-results.json
        results_format: json
        repo_token: ${{ secrets.GITHUB_TOKEN }}
