name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint code
      run: |
        pylint **/*.py

    - name: Lint Dockerfile
      run: |
        docker run --rm -i hadolint/hadolint < Dockerfile

    - name: Build Docker image
      run: |
        docker build -t myapp:latest .

    - name: Run unit tests
      run: |
        pytest

    - name: Run OpenSSF Scorecard
      uses: ossf/scorecard-action@v2
      with:
        results_file: results.json
        results_format: json  # تحقق من التنسيق الصحيح
        repo_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check if results file exists and is not empty
      run: |
        if [ -s results.json ]; then
          echo "Results file exists and is not empty."
        else
          echo "Results file does not exist or is empty."
          exit 1
        fi

    - name: Upload results to GitHub
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.json
