name: Version Check

on:
  push:
    branches:
      - main  # أو أي فرع تستخدمه

jobs:
  version-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install curl
      run: sudo apt-get install -y curl

    - name: Check /version endpoint
      run: |
        # استبدال <your-service-url> بعنوان الـ URL الصحيح حيث يعمل خدمتك
        url="http://18.234.140.13/version"
        expected_version="1.0.0" # استبداله بالإصدار المتوقع

        # استخدام curl للتحقق من الاستجابة
        response=$(curl -s -o response.txt -w "%{http_code}" $url)
        
        # التحقق من رمز الحالة HTTP
        if [ "$response" -ne 200 ]; then
          echo "Failed to get correct response from /version endpoint, HTTP code: $response"
          exit 1
        fi

        # قراءة النسخة من الاستجابة
        version=$(cat response.txt)
        
        # التحقق من النسخة المتوقعة
        if [ "$version" != "$expected_version" ]; then
          echo "Expected version $expected_version but got $version"
          exit 1
        fi

        echo "Version check passed"
